### ISSUE TITLE
Support for 4G modem

### ISSUE THREAD

**Issue by mohsenunique** [manio/aa-proxy-rs#4]
It would be great to add support for a 4G USB modem to enable internet access via WiFi. This enhancement will allow users to connect to the internet using a 4G USB modem, providing more flexibility and connectivity options. 

Is this feature feasible? Any guidance on how to implement it would be greatly appreciated.

**Comment by gamelaster** [comment]
This is more question for https://github.com/nisargjhaveri/WirelessAndroidAutoDongle project.

**Comment by manio** [comment]
Exactly as @gamelaster said: this project is using buildroot linux from WirelessAndroidAutoDongle. Closing.
